version: '3.7'
services:
  drone-delivery-web:
    build: ./web
    ports:
      - '8080:8080'
    environment:
      - BASE_URL=http://localhost:3000
    depends_on:
      - drone-delivery-server

  drone-delivery-server:
    build: ./server
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
